#!/bin/bash
# chkconfig: 345 96 14
# description: The Dubbo Service Script,running by dubbo user.
# author: tangcw
# version:1.5
  
#defined JAVA_HOME
source /etc/profile
#export JAVA_HOME=/usr/local/jdk1.8
if [ -z "$JAVACMD" ] ; then
  if [ -n "$JAVA_HOME"  ] ; then
    JAVACMD="$JAVA_HOME/bin/java"
  else
    JAVACMD=`which java`
  fi
fi
if [ ! -x "$JAVACMD" ] ; then
  echo "Error: JAVA_HOME is not defined correctly."
  echo "  We cannot execute $JAVACMD"
  exit 1
fi
#defined project
project_name=dock_service #此处修改为项目的名字
 
#defined variables
dubbo_path=/data/dubbo/
CONF_DIR=$dubbo_path$project_name/conf
LIB_DIR=$dubbo_path$project_name/lib
#JAVA_OPTS=" -server -Xms512m -Xmx512m"
JAVA_OPTS="-server -Xms2G -Xmx2G -Xss256K -XX:PermSize=128M -XX:MaxPermSize=256M -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+UseCMSCompactAtFullCollection -XX:+DisableExplicitGC -XX:+PrintGCDetails -Xloggc:${LOGS_DIR}/gc.log -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=${LOGS_DIR}/common_service.dump -Djava.net.preferIPv4Stack=true"
LIB_JARS=`ls ${LIB_DIR} | grep .jar | awk '{print "'${LIB_DIR}'/"$0}' | tr "\n" ":"`
#log=`grep "dubbo.logback.file" ${CONF_DIR}/dubbo.properties | awk -F= '{print $2}'`
STDOUT_FILE=/data/logs/dock.log #此处需根据特定项目修改成要打印的启动日志文件，可以写死。
 
#dock-service根据需要改成特定项目名称， -Ddisconf.env=改成当前执行的环境， -Ddisconf.conf_server_host=改为对应环境disconf的ip
APP_START_OPTS="-Ddisconf.app=dock-service -Ddisconf.env=demo -Ddisconf.version=1_0_0 -Ddisconf.enable.remote.conf=true -Ddisconf.conf_server_host=10.0.18.23 -Ddisconf.user_define_download_dir=/data/conf/$project_name/disconf/download"
if [ ! -d /data/conf/$project_name/disconf/download ];then
   mkdir /data/conf/$project_name/disconf/download -p
   chown -R dubbo.dubbo /data/conf/ &> /dev/null
fi

startup() {
   if [ $UID -eq 0 ];then
     su - dubbo -c "$JAVACMD ${JAVA_OPTS} ${APP_START_OPTS} -classpath ${CONF_DIR}:${LIB_JARS} com.alibaba.dubbo.container.Main $* > ${STDOUT_FILE} 2>&1 &"
   elif [ `whoami` == "dubbo" ];then
     $JAVACMD ${JAVA_OPTS} ${APP_START_OPTS} -classpath ${CONF_DIR}:${LIB_JARS} com.alibaba.dubbo.container.Main $* > ${STDOUT_FILE} 2>&1 &
   else
     echo "Please use dubbo or root start dubbo service"
   fi
}

#functions
start() {
   local PIDS=`ps -ef | grep ${project_name} | grep -v grep | grep java | awk '{print $2}'`
   if [ -n "$PIDS" ]; then
     echo "ERROR: The ${project_name} is running!"
   else
     echo -ne "Starting ${project_name}\r"
     startup
     local PID=`ps -ef | grep ${project_name} | grep -v grep | grep java | awk '{print $2}'`
     if [ -n "$PID"  ];then
       echo -e "\t\t\t\t\t[\e[1;32m ok \e[0m]"
     else
       echo -e "\t\t\t\t\t[\e[1;31m fail \e[0m]"
     fi
   fi
}
stop() {
   local PIDS=`ps -ef | grep ${project_name} | grep -v grep | grep java | awk '{print $2}'`
   if [ -z "$PIDS" ]; then
     echo "ERROR: The ${project_name} does not started!"
   else
     echo -ne "Stopping ${project_name}\r"
     if [ -n "$PIDS" ];then
       kill -9 $PIDS &> /dev/null
       [ "$?" -eq 0 ] && echo -e "\t\t\t\t\t[\e[1;32m ok \e[0m]" || echo -e "\t\t\t\t\t[\e[1;31m fail \e[0m]"
     fi
   fi
}
#
#
case $1 in
start)
   $1 
   ;;
stop)
   $1
   ;;
restart)
   stop 
   sleep 1
   start
   ;;
*)
   echo "Usage: dubbo [start|stop|restart]"
   exit 1
   ;;
esac
exit 0
